# first stage
FROM node AS builder
WORKDIR /app
COPY package.json .

RUN npm install --legacy-peer-deps 

COPY . ./

ARG BASE_URL
ENV REACT_APP_SERVER=${BASE_URL}

RUN npm run build

# second stage

FROM caddy:2.6.4-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /app/build /srv

EXPOSE 80
EXPOSE 443